spring:
  datasource:
    url: jdbc:mysql://mysql.czyymmc26gs1.ap-northeast-2.rds.amazonaws.com:3306/festspot_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: FestSpot!226$
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.festspot.dev.domain.entity

jwt:
  secret: 3f7f10f708f42014ca2aaeb995d18a2cd294a6e391965cc27258c41953bb1419146540df87698c1aad4d07f4775df24dedfdb4bad4af2eb7b084c1e00f485dbf
