spring:
  datasource:
    url: jdbc:mysql://mysql.czyymmc26gs1.ap-northeast-2.rds.amazonaws.com:3306/festspot_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 1Q2w3e4r!
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 394107758566-74poii5i9v4434asqut46dq6d2m1n6sd.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          kakao:
            client-id: fa7002132185636a564bb0f17b71211f
            client-secret: k5Yb7SOQ0pMBGc6YpQvfssqNwo65gvk6
            scope: profile_nickname, account_email, profile_image
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
          naver:
            client-id: l7L0pZWzPfhCWRV0bq7U
            client-secret: JBdwqNhBql
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - nickname
              - email
              - profile_image
            client-name: naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.festspot.dev.domain.entity

jwt:
  secret: 1968b508680fb182cb5ce95345b03eecbe3918487fc8bc8338a9a0ccb2ed141158df8f25f62f13ad80c60b04e5616989f6efec0fd27ab857eecc724f197759b7
